const data = {
  products: [
    {
      _id: 1,
      name: 'Nike Slim shirt',
      slug: '咪嚕',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: 2,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt1',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: 3,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt2',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: 4,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt3',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: 5,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt4',
      category: 'Shirts',
      image: 'images/p5.jpg',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: 6,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt5',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
  ],
};

export default data;
